# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from unittest.mock import patch
from tkinter import messagebox, Tk, Text, END
from Captcha_Genrator import verify

class TestVerifyCaptcha(unittest.TestCase):

    def setUp(self):
        self.root = Tk()

    @patch('Captcha_Genrator.random', 123) 
    @patch('Captcha_Genrator.t1') 
    @patch('Captcha_Genrator.messagebox')
    def test_Verify_96c841bd06(self, mock_msgbox, mock_t1): 

        # Set up the Text widget
        mock_t1.get.return_value = '123' 

        # Scenario where verification is successful
        verify()
        mock_msgbox.showinfo.assert_called_with("success", "verified")
        mock_msgbox.reset_mock()

        # Scenario where verification fails
        mock_t1.get.return_value = '124'
        verify()
        mock_msgbox.showinfo.assert_called_with("Alert", "Not verified")

if __name__ == '__main__':
    unittest.main()
