# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

# Creation of 'capture_video_frames' file with 'ExtractFrames' class used in our test suite

import os
import shutil

class ExtractFrames:
    def __init__(self, file_path):   
        self.directory = "captured_frames"
        self.file_path = file_path
        if os.path.exists(self.directory):
            shutil.rmtree(self.directory)
        os.mkdir(self.directory)
