# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import os
import shutil

def initialize_and_create_dir(file_path):        
    directory = "captured_frames"
    file_path = file_path
    if os.path.exists(directory):
        shutil.rmtree(directory)
    os.mkdir(directory)
