# ********RoostGPT********

# Test generated by RoostGPT for test multi-api-karate using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /me_get for http method type GET 
# RoostTestHash=4f4e94f0a0
# 
# 

# ********RoostGPT********
Feature: User Information

  Background:
    * def baseURL = karate.properties['CIRCLECI_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = false
    * configure headers = { Accept: 'application/json' }

  Scenario: Get User Information with API Key Authorization
    * def authToken = karate.properties['Circle-Token']
    * configure headers = { Circle-Token: '#(authToken)' }
    Given path '/me'
    When method get
    Then status 200
    And match response ==
      """
      {
        id: '#uuid',
        login: '#string',
        name: '#string'
      }
      """

  Scenario: Get User Information with Basic Authorization
    * def username = karate.properties['AUTH_USERNAME_AKSHAT']
    * def password = karate.properties['AUTH_PASSWORD_AKSHAT']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)' }
    Given path '/me'
    When method get
    Then status 200
    And match response ==
      """
      {
        id: '#uuid',
        login: '#string',
        name: '#string'
      }
      """

  Scenario: Get User Information with Query Parameter Authorization
    * def authToken = karate.properties['circle-token']
    Given path '/me'
    And param circle-token = authToken
    When method get
    Then status 200
    And match response ==
      """
      {
        id: '#uuid',
        login: '#string',
        name: '#string'
      }
      """

  Scenario: Get User Information with Invalid API Key Authorization
    * configure headers = { Circle-Token: 'invalid_token' }
    Given path '/me'
    When method get
    Then status 401
    And match response == { message: '#string' }

  Scenario: Get User Information with Invalid Basic Authorization
    * def username = 'invalid_user'
    * def password = 'invalid_pass'
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)' }
    Given path '/me'
    When method get
    Then status 401
    And match response == { message: '#string' }

  Scenario: Get User Information with Invalid Query Parameter Authorization
    * def authToken = 'invalid_token'
    Given path '/me'
    And param circle-token = authToken
    When method get
    Then status 401
    And match response == { message: '#string' }
