# ********RoostGPT********

# Test generated by RoostGPT for test multi-api-karate using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=bc8f34e70c
# 
# 

# ********RoostGPT********
Feature: Find pet by ID

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = false
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Find pet by ID with valid petId and API Key auth
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status 200
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[]'
    And match response.tags == '#[]'
    And match response.status == '#string'

    Examples:
      | read('pet_petId_get.csv') |

  Scenario Outline: Find pet by ID with valid petId and OAuth2 auth
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status 200
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[]'
    And match response.tags == '#[]'
    And match response.status == '#string'

    Examples:
      | read('pet_petId_get.csv') |

  Scenario Outline: Find pet by ID with invalid petId and API Key auth
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status 404
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | petId |
      |  9999 |

  Scenario Outline: Find pet by ID with invalid petId and OAuth2 auth
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status 404
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | petId |
      |  9999 |

  Scenario Outline: Find pet by ID with invalid petId format and API Key auth
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status 400
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | petId |
      | abc   |

  Scenario Outline: Find pet by ID with invalid petId format and OAuth2 auth
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status 400
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | petId |
      | abc   |
