# ********RoostGPT********

# Test generated by RoostGPT for test multi-api-karate using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=bc8f34e70c
# 
# 

# ********RoostGPT********
Feature: Find pet by ID

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = false
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Find pet by ID with valid petId using API Key
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status <status>
    And match response == '#? _ == null || typeof _ == "object"'
    And match response.id == '#? _ == null || typeof _ == "number"'
    And match response.name == '#? _ == null || typeof _ == "string"'
    And match response.category == '#? _ == null || typeof _ == "object"'
    And match response.category.id == '#? _ == null || typeof _ == "number"'
    And match response.category.name == '#? _ == null || typeof _ == "string"'
    And match response.photoUrls == '#? _ == null || typeof _ == "array"'
    And match each response.photoUrls[*].photoUrl == '#? _ == null || typeof _ == "string"'
    And match response.tags == '#? _ == null || typeof _ == "array"'
    And match each response.tags[*].id == '#? _ == null || typeof _ == "number"'
    And match each response.tags[*].name == '#? _ == null || typeof _ == "string"'
    And match response.status == '#? _ == null || typeof _ == "string"'
    And match response.status == '#? _ == null || _ == "available" || _ == "pending" || _ == "sold"'

    Examples:
      | petId | status |
      |     1 |    200 |
      |     2 |    200 |
      |     3 |    200 |

  Scenario Outline: Find pet by ID with valid petId using OAuth2
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN_AKSHAT']
    * configure headers = { Authorization: '#(authToken)' }
    Given path '/pet/<petId>'
    When method get
    Then status <status>
    And match response == '#? _ == null || typeof _ == "object"'
    And match response.id == '#? _ == null || typeof _ == "number"'
    And match response.name == '#? _ == null || typeof _ == "string"'
    And match response.category == '#? _ == null || typeof _ == "object"'
    And match response.category.id == '#? _ == null || typeof _ == "number"'
    And match response.category.name == '#? _ == null || typeof _ == "string"'
    And match response.photoUrls == '#? _ == null || typeof _ == "array"'
    And match each response.photoUrls[*].photoUrl == '#? _ == null || typeof _ == "string"'
    And match response.tags == '#? _ == null || typeof _ == "array"'
    And match each response.tags[*].id == '#? _ == null || typeof _ == "number"'
    And match each response.tags[*].name == '#? _ == null || typeof _ == "string"'
    And match response.status == '#? _ == null || typeof _ == "string"'
    And match response.status == '#? _ == null || _ == "available" || _ == "pending" || _ == "sold"'

    Examples:
      | petId | status |
      |     1 |    200 |
      |     2 |    200 |
      |     3 |    200 |

  Scenario: Find pet by ID with invalid petId using API Key
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    Given path '/pet/abc'
    When method get
    Then status 400

  Scenario: Find pet by ID with invalid petId using OAuth2
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN_AKSHAT']
    * configure headers = { Authorization: '#(authToken)' }
    Given path '/pet/abc'
    When method get
    Then status 400

  Scenario: Find pet by ID with non-existent petId using API Key
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    Given path '/pet/999999'
    When method get
    Then status 404

  Scenario: Find pet by ID with non-existent petId using OAuth2
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN_AKSHAT']
    * configure headers = { Authorization: '#(authToken)' }
    Given path '/pet/999999'
    When method get
    Then status 404
