# ********RoostGPT********

# Test generated by RoostGPT for test multi-api-karate using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=bc8f34e70c
# 
# 

# ********RoostGPT********
Feature: Find pet by ID

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = false
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Find pet by ID with API Key Authorization
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    Given path '/pet', <petId>
    When method get
    Then status <status>
    And match response ==
      """
      <response>
      """

    Examples:
      | petId | status | response                                                                                                                           |
      |    10 |    200 | { id: '#number', name: '#string', category: { id: '#number', name: '#string' }, photoUrls: '#[]', tags: '#[]', status: '#string' } |
      |   999 |    404 | { error: { code: '#number', message: '#string' } }                                                                                 |
      |    -1 |    400 | { error: { code: '#number', message: '#string' } }                                                                                 |

  Scenario Outline: Find pet by ID with OAuth2 Authorization
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    Given path '/pet', <petId>
    When method get
    Then status <status>
    And match response ==
      """
      <response>
      """

    Examples:
      | petId | status | response                                                                                                                           |
      |    10 |    200 | { id: '#number', name: '#string', category: { id: '#number', name: '#string' }, photoUrls: '#[]', tags: '#[]', status: '#string' } |
      |   999 |    404 | { error: { code: '#number', message: '#string' } }                                                                                 |
      |    -1 |    400 | { error: { code: '#number', message: '#string' } }                                                                                 |
