# ********RoostGPT********

# Test generated by RoostGPT for test multi-api-karate using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /products/{productId}_get for http method type GET 
# RoostTestHash=52a171b52e
# 
# 

# ********RoostGPT********
Feature: Find product by ID

  Background:
    * def baseURL = karate.properties['SWAGGER_MYPRODUCTS_OPENAPI_30_BASE_URL'] || karate.properties['BASE_URL']
    * url baseURL
    * configure report = true
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Find product by ID with valid productId
    Given path '/products', '/<productId>'
    When method get
    Then status 200
    And match response.id == '##number'
    And match response.name == '##string'
    And match response.description == '##string'
    And match response.price == '##number'

    Examples:
      | read('products_productId_get.csv') |

  Scenario Outline: Find product by ID with invalid productId
    Given path '/products', '/<productId>'
    When method get
    Then status 404

    Examples:
      | productId |
      |      9999 |
      |      8888 |
      |      7777 |
