# ********RoostGPT********

# Test generated by RoostGPT for test multi-api-karate using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /products/{productId}_get for http method type GET 
# RoostTestHash=52a171b52e
# 
# 

# ********RoostGPT********
Feature: Find product by ID

  Background:
    * def baseURL = karate.properties['SWAGGER_MYPRODUCTS_OPENAPI_30_BASE_URL'] || karate.properties['API_HOST_PRODUCTS']
    * url baseURL
    * configure report = true
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Verify successful retrieval of a product by ID
    Given path '/products', '/<productId>'
    When method GET
    Then status 200
    And match response == { id: '#number', name: '#string', description: '#string', price: '#number' }

    Examples:
      | read('products_productId_get.csv') |

  Scenario: Verify response for non-existent product ID
    Given path '/products', '/9999999999'
    When method GET
    Then status 404
