# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
import random
from ball_bounce import Ball

def test___init___f98f6ecd53():
    # Create an instance of Ball
    ball = Ball()

    assert hasattr(ball, 'velocityX'), "`velocityX` doesn't exist"
    assert hasattr(ball, 'velocityY'), "`velocityY` doesn't exist"
    assert hasattr(ball, 'X'), "`X` doesn't exist"
    assert hasattr(ball, 'Y'), "`Y` doesn't exist"

    assert type(ball.velocityX) == int, "`velocityX` is not int"
    assert type(ball.velocityY) == int, "`velocityY` is not int"
    assert type(ball.X) == int, "`X` is not int"
    assert type(ball.Y) == int, "`Y` is not int"

    assert ball.velocityX == 4, "`velocityX` is not 4"
    assert ball.velocityY == 4, "`velocityY` is not 4"
    assert 0 <= ball.X <= 768, "`X` is not between 0 and 768"
    assert 0 <= ball.Y <= 350, "`Y` is not between 0 and 350"

