# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import random
from ball_bounce import BounceBall    # Assuming that the __init__ method you have provided is in a class named BounceBall
import unittest

class TestBallBounce(unittest.TestCase):
  
    def test___init___f98f6ecd53(self):
        ball = BounceBall()              # Create an instance of BounceBall
        # Now we want to test that all the variables have the correct values.

        # Test if velocityX and velocityY have the correct values.
        self.assertEqual(ball.velocityX, 4)  
        self.assertEqual(ball.velocityY, 4)

        # Test if X and Y are in their correct ranges.
        self.assertTrue(0 <= ball.X <= 768)
        self.assertTrue(0 <= ball.Y <= 350)

if __name__ == '__main__':
    unittest.main()
