# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pygame
import pytest
from ball_bounce import Ball

def test_Move_ball_783a83baa3():
    # Initialize pygame
    pygame.init()

    # Test 1 : Check for correct movement
    ball_item1 = Ball(100, 100, 10, 20)  
    ball_item1.move_ball()
    assert ball_item1.X == 110  // TODO: Change X and Y values as per your actual result
    assert ball_item1.Y == 120  // TODO: Change X and Y values as per your actual result

    # Test 2 : Check for correct bouncing on hitting x limits
    ball_item2 = Ball(765, 100, 10, 20)
    ball_item2.move_ball()
    assert ball_item2.X == 755  // TODO: Change X and Y values as per your actual result

    # Test 3 : Check for correct bouncing on hitting y limits from top
    ball_item3 = Ball(100, -10, 10, -20) 
    ball_item3.move_ball()
    assert ball_item3.Y == 0    // TODO: Change X and Y values as per your actual result

    # Test 4 : Check for correct bouncing on hitting y limits from bottom
    ball_item4 = Ball(100, 575, 10, 20)
    ball_item4.move_ball()
    assert ball_item4.Y == 565  // TODO: Change X and Y values as per your actual result

    pygame.quit()

# The tests can be run using the following command in the terminal
# pytest -v test_ball_bounce.py -k test_Move_ball_783a83baa3
