# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
import calculate 

class TestCalculate(unittest.TestCase):

    def test_month_days(self):
        # Test case for January (or any other month with 31 days)
        # When year is a leap year
        result = calculate.month_days(1, True)
        self.assertEqual(result, 31)

        # Test case for April (or any other month with 30 days)
        # When year is a leap year
        result = calculate.month_days(4, True)
        self.assertEqual(result, 30)

        # Test case for February when year is a leap year
        result = calculate.month_days(2, True)
        self.assertEqual(result, 29)
        
        # Test case for February when year is not a leap year
        result = calculate.month_days(2, False)
        self.assertEqual(result, 28)

if __name__ == '__main__':
    unittest.main()
