# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from add import add_numbers     # TODO: replace "add" with the name of the file where add_numbers is defined

class TestAddNumbers(unittest.TestCase):
    
    def test_Add_numbers_4beee899f4_positive(self):
        self.assertEqual(add_numbers(3, 2), 5, "Adding 3 and 2 should be 5")
 
    def test_Add_numbers_4beee899f4_negative(self):
        self.assertEqual(add_numbers(-3, -2), -5, "Adding -3 and -2 should be -5")

if __name__ == "__main__":
    unittest.main()
