# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

# Import necessary libraries
import unittest
from calculate import judge_leap_year

class TestJudgeLeap(unittest.TestCase):
    def test_Judge_leap_year_4548bc7362(self):
        # Test the case where year is a leap year
        self.assertTrue(judge_leap_year(2020), "Test failed: 2020 is a Leap year.")

        # Test the case where year is not a leap year
        self.assertFalse(judge_leap_year(2019), "Test failed: 2019 is not a Leap year.")

        # Test when year is a string
        with self.assertRaises(TypeError):
            judge_leap_year("2020")

        # Test when year is a float
        with self.assertRaises(TypeError):
            judge_leap_year(2020.234)

        # Test when year is negative
        with self.assertRaises(ValueError):
            judge_leap_year(-2020)

if __name__ == '__main__':
    unittest.main()
