# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
from add import add_numbers

def test_Add_numbers_4beee899f4():
    # Test case 1: Positive numbers
    result = add_numbers(5, 3)
    assert result == 8, "Test case 1 failed: Adding 5 and 3 should be 8"

    # Test case 2: Negative numbers
    result = add_numbers(-4, -6)
    assert result == -10, "Test case 2 failed: Adding -4 and -6 should be -10"

    # Test case 3: positive and negative number
    result = add_numbers(7, -5)
    assert result == 2, "Test case 3 failed: Adding 7 and -5 should be 2"

    # Test case 4: zero and a number
    result = add_numbers(0, 5)
    assert result == 5, "Test case 4 failed: Adding 0 and 5 should be 5"

    # Test case 5: decimal numbers
    result = add_numbers(2.5, 3.5)
    assert result == 6.0, "Test case 5 failed: Adding 2.5 and 3.5 should be 6.0"

    print("All test cases pass")

test_Add_numbers_4beee899f4()
