# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
from calendar import isleap
import calculate

def test_judge_leap_year():
    assert calculate.judge_leap_year(2000) == isleap(2000)
    assert calculate.judge_leap_year(1900) == isleap(1900)
    assert calculate.judge_leap_year(2004) == isleap(2004)
    assert calculate.judge_leap_year(2100) == isleap(2100)
    
def test_judge_leap_year_invalid_input():
    with pytest.raises(TypeError):
        calculate.judge_leap_year('2000') # Should raise TypeError as the year is a string
    with pytest.raises(TypeError):
        calculate.judge_leap_year(None) # Should raise TypeError as the year is None

