# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
from calendar import isleap
from calculate import judge_leap_year

def test_Judge_leap_year_4548bc7362():
    # Test for a known leap year (like 2020)
    assert judge_leap_year(2020) == True, "Test case 1 failed"
    print("Test case 1 passed")

    # Test for a known non-leap year (like 2019)
    assert judge_leap_year(2019) == False, "Test case 2 failed"
    print("Test case 2 passed")

    # Test for a year that is divisible by 100 and not by 400 (like 1900), which is not a leap year according to the Gregorian calendar:
    assert judge_leap_year(1900) == False, "Test case 3 failed"
    print("Test case 3 passed")

    # Test for a year that is divisible by 400 (like 2000), which is a leap year according to the Gregorian calendar:
    assert judge_leap_year(2000) == True, "Test case 4 failed"
    print("Test case 4 passed")

test_Judge_leap_year_4548bc7362()
