# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from calendar import isleap

def month_days(month, leap_year):
    if month in [1, 3, 5, 7, 8, 10, 12]:
        return 31
    elif month in [4, 6, 9, 11]:
        return 30
    elif month == 2 and leap_year:
        return 29
    elif month == 2 and (not leap_year):
        return 28

class TestMonthDaysMethod(unittest.TestCase):
    def test_Month_days_5dd3c5e333(self):
        self.assertEqual(month_days(12, False), 31) # test if December has 31 days.
        self.assertEqual(month_days(4, False), 30) # test if April has 30 days.
        self.assertEqual(month_days(2, True), 29) # test if February has 29 days in a leap year.
        self.assertEqual(month_days(2, False), 28) # test if February has 28 days in a non-leap year.

if __name__ == "__main__":
    unittest.main()
