# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
from tkinter import *
from billing_system import welcome_bill

class TestBilling:

    # simulate a situation where the method works properly
    @pytest.fixture 
    def bill(self):
        class Bill:
            bill_no = StringVar(value='1234')
            c_name = StringVar(value='John Doe')
            c_phone = StringVar(value='1234567890')
            txtarea = Text()
        return Bill()

    # Test case 1: Checking the first few lines of the welcome_bill method
    def test_Welcome_bill_8a5d8ffb72(self, bill):
        welcome_bill(bill)
        lines = bill.txtarea.get('1.0', 'end-1c').split("\n")
        assert lines[0] == '\tWelcome Webcode Retail'
        assert lines[1] == ' Bill Number:1234'
        assert lines[2] == 'Customer Name:John Doe'
        assert lines[3] == 'Phone Number1234567890'
        assert lines[4] == '================================'
        assert lines[5] == 'Products\t\tQTY\t\tPrice'

    # Test case 2: Checking if the Text widget is cleared with each call
    def test_Welcome_bill_8a5d8ffb72_reset(self, bill):
        welcome_bill(bill)
        welcome_bill(bill)
        lines = bill.txtarea.get('1.0', 'end-1c').split("\n")
        assert len(lines) == 7   #TODO: This number should be equal to the number of new lines inserted in each method call
