# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from unittest.mock import patch
from tkinter import Tk
from billing_system import Bill_App

class TestBillApp(unittest.TestCase):

    @patch('billing_system.messagebox.askyesno')
    def test_Exit_app_a10beac2f8(self, mock_messagebox):
        root = Tk()
        app = Bill_App(root)
        
        mock_messagebox.return_value = True
        with self.assertRaises(SystemExit):
            app.exit_app()
            root.mainloop()

        mock_messagebox.return_value = False
        try:
            app.exit_app()
            root.mainloop()
        except SystemExit:
            self.fail('SystemExit raised unexpectedly!')


if __name__ == "__main__":
    unittest.main()
