# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
from biling_system import BillSystem  # assuming BillSystem is the name of the class containing clear_data

def test_Clear_data_75709990c7():
    # assuming BillSystem is the name of the class containing clear_data
    test_object = BillSystem()  

    # Set initial values
    test_object.sanitizer.set(5)
    test_object.mask.set(3)
    test_object.hand_gloves.set(7)
    # repeat for all the other attributes...

    # Assuming that messagebox.askyesno will return 1
    with pytest.patch('tkinter.messagebox.askyesno', return_value=1):
        test_object.clear_data()

    # Now check that every value is reset
    assert test_object.sanitizer.get() == 0
    assert test_object.mask.get() == 0
    assert test_object.hand_gloves.get() == 0
    # repeat for all other attributes...
