# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
from unittest.mock import MagicMock, patch
from tkinter import messagebox
from billing_system import save_bill

class TestBillingSystem:

    @patch("tkinter.messagebox.showinfo")
    @patch("tkinter.messagebox.askyesno")
    @patch("builtins.open")
    @patch.object(BillingSystem, 'txtarea')
    @patch.object(BillingSystem, 'bill_no')
    def test_Save_bill_4312133209(self, mock_bill_no, mock_txtarea, mock_open, mock_askyesno, mock_showinfo):
        bs = BillingSystem()

        # Test when user clicks Yes on messagebox and successfully save the file
        mock_askyesno.return_value = 1
        mock_txtarea.get.return_value = "Bill Data"
        mock_bill_no.get.return_value = '4312133209'
        bs.save_bill()
        mock_open.assert_called_with('bills/4312133209.txt', 'w')
        mock_showinfo.assert_called_with("Saved", "Bill no:4312133209 Saved Successfully")

        # Test when user clicks No on messagebox
        mock_askyesno.return_value = 0
        bs.save_bill()
        mock_askyesno.assert_called_with("Save Bill", "Do you want to save the bill?")
