# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import os
from tkinter import messagebox

def find_bill(search_bill, txtarea):
    present = "no"
    for i in os.listdir("bills/"):
        if i.split('.')[0] == search_bill:
            with open(f"bills/{i}", "r") as f1:
                txtarea.delete("1.0", "end")
                for d in f1:
                    txtarea.insert("end", d)
                present = "yes"
                break
    if present == "no":
        messagebox.showerror("Error", "Invalid Bill No")
