# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import pytest
from billing_system import BillingSystem

# Test cases to verify the 'total' function

def test_Total_11f4f7312f():
    # Test Case 1: Check normal case
    shop = BillingSystem()

    shop.hand_gloves.set(1)
    shop.sanitizer.set(3)
    shop.mask.set(5)
    shop.rice.set(2)
    shop.food_oil.set(2)
    shop.sprite.set(4)
    shop.limka.set(4)

    shop.total()
    assert shop.total_bill == 239.7, 'Test Case 1 Failed'

    # Test Case 2: Check when all quantities are zero
    shop = BillingSystem()

    shop.hand_gloves.set(0)
    shop.sanitizer.set(0)
    shop.mask.set(0)
    shop.dettol.set(0)
    shop.newsprin.set(0)
    shop.thermal_gun.set(0)
    shop.rice.set(0)
    shop.food_oil.set(0)
    shop.wheat.set(0)
    shop.daal.set(0)
    shop.flour.set(0)
    shop.maggi.set(0)
    shop.sprite.set(0)
    shop.limka.set(0)
    shop.mazza.set(0)
    shop.coke.set(0)
    shop.fanta.set(0)
    shop.mountain_duo.set(0)

    shop.total()
    assert shop.total_bill == 0, 'Test Case 2 Failed'

    # TODO: Add more tests here to fully cover all scenarios

    print('All test cases pass')

if __name__ == '__main__':
    test_Total_11f4f7312f()
