# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

def exit_app(self, confirm_exit):
    if confirm_exit:
        self.root.destroy()
    return confirm_exit
