# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

# Save the content of the text area into a file
def save_bill_content(bill_no, bill_content):
    try:
        with open("bills/" + str(bill_no) + ".txt", "w") as f:
            f.write(bill_content)
            return True
    except Exception as e:
        return False
