# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

def check_alarm(current_time, set_alarm_time): 
    if current_time == set_alarm_time:
        return True
    else:
        return False
