# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import requests
import time
from util import get_baidu_poi
from unittest.mock import patch, mock_open

class TestGetBaiduPOI(unittest.TestCase):

    @patch("requests.get")
    @patch("time.strftime")
    @patch("builtins.open", new_callable=mock_open)
    def test_Get_baidu_poi_50efe74a12(self, mock_file, mock_time, mock_requests):
        # TODO: Define your own roi_key, city_str, baidu_ak and output.
        roi_key = "test"
        city_str = "Shanghai"
        baidu_ak = "YOUR_OWN_BAIDU_AK"
        output = "/path/to/your/output/directory"

        mock_time.return_value = "2022-01-01"
        mock_requests.return_value.text = '{"results": []}'
        get_baidu_poi(roi_key, city_str, baidu_ak, output)
        mock_file.assert_called_once_with(output + "/" + "2022-01-01" + ".log", "a+", encoding="utf-8")

        mock_requests.return_value.text = '{"results": [{"name": "poi1", "location": {"lat": 30.657, "lng": 104.066}, "area":"Sichuan", "address":"Chengdu"}]}'
        get_baidu_poi(roi_key, city_str, baidu_ak, output)
        mock_file.assert_called_with(output + "/" + "2022-01-01" + ".txt", "a+", encoding="utf-8")
        
if __name__ == "__main__":
    unittest.main()
