# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

from make_art import print_out_ascii
import numpy as np
import pytest

def test_print_out_ascii_d593277e76(capsys): 

  # Test case 1: Success case 
  # TODO: User need to change array values
  array1 = np.array([
      [1, 2, 3], 
      [4, 5, 6], 
      [7, 8, 9]
  ])
  symbols_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
  print_out_ascii(array1)
  captured = capsys.readouterr()
  assert captured.out == "abc\nfgh\nijb\n"
        
  # Test case 2: Not an Array case
  array2 = "123456789"
  with pytest.raises(TypeError):
      print_out_ascii(array2)

  # Test case 3: Array elements out of scope
  array3 = np.array([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']])
  with pytest.raises(ValueError):
      print_out_ascii(array3)

  # Test case 4: Empty array
  array4 = np.array([])
  print_out_ascii(array4)
  captured = capsys.readouterr()
  assert captured.out == "\n"
