# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roost-gpt4-32k

import numpy as np
import cv2
from your_app import img_to_ascii  # TODO: Change 'your_app' to the name of the application where img_to_ascii is defined.
